server:
  port: 8082

mqtt:
  psk_file: /opt/homebrew/etc/mosquitto/certs/psk_file.txt

auth0:
  issuer: "https://dissertationuaa.eu.auth0.com/"
  client-id: vLH1l8zt2TiJGi36lsg3Bv9LpaWkIWlf
  audience: secureiot
  grant-type: client_credentials

vault:
  uri: https://127.0.0.1:8200/
  token: hvs.CAESIHzytHe8YEuGdw-YBOHmSVbqsM_Fu1gGnWuTK_VCtZnRGh4KHGh2cy44MTNjdWNLOG1ST0twRUVVMUd1dThNdDU