server:
  port: 8082

mqtt:
  psk_file: /etc/mosquitto/certs/psk_file.txt

auth0:
  issuer: "https://dissertationuaa.eu.auth0.com/"
  client-id: vLH1l8zt2TiJGi36lsg3Bv9LpaWkIWlf
  audience: secureiot
  grant-type: client_credentials

vault:
  uri: https://127.0.0.1:8200/
  token: ${WRAPPING_TOKEN}

gw:
  uri: http://127.0.0.1:8080