spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/andreiczc/dissertation_configs.git

server:
  port: 8800
  ssl:
    enabled: true
    key-alias: configserver
    key-store-password: pass
    key-store: classpath:server.p12
    key-store-type: PKCS12