server:
  port: 8080

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dissertationuaa.eu.auth0.com/
  cloud:
    gateway:
      routes:
        - id: dbapp
          uri: lb://dbapp
          predicates:
            - Path=/iot/**
          filters:
            - StripPrefix=1
            - CircuitBreaker=dbapp
    config:
      import-check:
        enabled: false

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
