spring:
  application:
    name: registry
  cloud:
    config:
      import: configserver:https://config-server:8800

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false