version: '3.9'
services:
  zipkin:
    image: openzipkin/zipkin
    networks:
      - iot-net
  mysql:
    image: mysql
    networks:
      - iot-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  config-server:
    image: config-server
    networks:
      - iot-net
  registry:
    image: registry
    networks:
      - iot-net
    depends_on:
      - config-server
  dbapp:
    image: dbapp
    networks:
      - iot-net
    depends_on:
      - registry
      - mysql
      - config-server
    environment:
      - WRAPPING_TOKEN=hvs.CAESIMrexEUDg6_P7UmFlpKMKhp_nyX0udJWwYkUF7jWINhNGh4KHGh2cy5uaTFNYjd5R2FGMllPcllBVkxxZHdCSVc
  gateway:
    image: gateway
    restart: unless-stopped
    networks:
      - iot-net
    depends_on:
      - registry
      - zipkin
      - dbapp
      - config-server
    ports:
      - "8080:8080"
networks:
  iot-net:
volumes:
  dbvol: