version: '3.9'
services:
  zipkin:
    image: openzipkin/zipkin
    networks:
      - iot-net
    ports:
      - "9411:9411"
  mysql:
    image: arm64v8/mysql:oracle
    networks:
      - iot-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - dbvol:/var/lib/mysql
  configserver:
    image: config-server
    networks:
      - iot-net
  mqtt-client:
    image: mqtt-client
    network_mode: host
    environment:
      - WRAPPING_TOKEN=hvs.CAESIFLVJMRHHIutuJsxzS9ccgFfs3svJs1B7pp-m-suN1bTGh4KHGh2cy5nek54N0c4TGlCbmdOQ3Zaa1NoNnpOMzI
  registry:
    image: registry
    networks:
      - iot-net
    depends_on:
      - config-server
  dbapp:
    image: dbapp
    networks:
      - iot-net
    depends_on:
      - registry
      - mysql
      - config-server
      - zipkin
    environment:
      - WRAPPING_TOKEN=hvs.CAESICUgBWyxi-iC92RDKEVoNGJYjU0aLMnZU6HF0EQjdGEcGh4KHGh2cy5RakFmU3BieWt5eUxOSG14eVJBSGZESlA
  gateway:
    image: gateway
    restart: unless-stopped
    networks:
      - iot-net
    depends_on:
      - registry
      - zipkin
      - dbapp
      - config-server
    ports:
      - "8080:8080"
networks:
  iot-net:
volumes:
  dbvol:
