version: '3.9'
services:
  zipkin:
    image: openzipkin/zipkin
    networks:
      - iot-net
  mysql:
    image: arm64v8/mysql:oracle
    networks:
      - iot-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - dbvol:/var/lib/mysql
  config-server:
    image: config-server
    networks:
      - iot-net
  mqtt-client:
    image: mqtt-client
    network_mode: host
    environment:
      - WRAPPING_TOKEN=hvs.CAESIC2vBq6j7vIGqU2Vd_H63PaEkQR1C3y522AP-yfup09kGh4KHGh2cy5IT0c3eWg2SmNEOE9DTmxhQ0FuTU1HTzI
  registry:
    image: registry
    networks:
      - iot-net
    depends_on:
      - config-server
  dbapp:
    image: dbapp
    networks:
      - iot-net
    depends_on:
      - registry
      - mysql
      - config-server
      - zipkin
    environment:
      - WRAPPING_TOKEN=hvs.CAESIAHAE2xhqGvXix17MHdepwGtcAAUcXHlGIMW0e3FLP22Gh4KHGh2cy5NemJCZTRNZEJHb2lQU2hvVEIyRUNqRWI
  gateway:
    image: gateway
    restart: unless-stopped
    networks:
      - iot-net
    depends_on:
      - registry
      - zipkin
      - dbapp
      - config-server
    ports:
      - "8080:8080"
networks:
  iot-net:
volumes:
  dbvol:
