server:
  port: 8081

auth0:
  audience: secure_iot

spring:
  application:
    name: dbapp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dissertationuaa.eu.auth0.com/
  datasource:
    url: jdbc:mysql://localhost:3306/secureiot
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

vault:
  uri: https://130.162.253.10:8200/
  token: "hvs.CAESILy1pF_U-A9rKWPbX9kn4VRhuPMSuU8jcwPIAwoZyr4ZGh4KHGh2cy5zdXZ4U3JkRndaTks1c1lTa2Q2eVg1eEI"